# Generated by Django 5.0.7 on 2024-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('length', models.DurationField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='video_media/')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('show_type', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=20)),
            ],
        ),
    ]
