# Generated by Django 5.0.7 on 2024-07-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstreambackend', '0003_show_imdb_rating_show_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='release_date',
        ),
    ]
