# Generated by Django 5.0.7 on 2024-07-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstreambackend', '0004_remove_show_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='length',
        ),
    ]
